### PR TITLE
Added dash patterns

### PR DESCRIPTION
**Pull request by a-ludi**
I implemented the methods for dealing with dash patterns in strokes (see [below](https://github.com/AuburnSounds/printed/compare/master...a-ludi:feature/dash-patterns?expand=1#diff-d0dd05d68aaeea7eb17cad4acfeca86324816636fcd331b55069ec5b0e068de6R81-R102))

### CODE REVIEW

**Review by p0nce — COMMENTED** [review]
Will be merged if:
- remove `@property`, it is currently a near-useless keyword. It will work the same for the user.
- `normalizeLineDashPattern` and `isValidLineDashPattern` are not part of the API interface so they should not go in `irenderer.d` (you can even duplicate them if needed)

**Comment by a-ludi** [comment]
The procedures `normalizeLineDashPattern` and `isValidLineDashPattern` implement steps 2) and 3) described in the implementation of `setLineDash()` in the [W3c standard](https://www.w3.org/TR/2dcontext/):

> When the setLineDash() method is invoked, it must run the following steps:
>
> 1. Let a be a copy of the array provided as the argument.
> 2. If any value in the array is not finite (e.g. an Infinity or a NaN value), or if any value is negative (less than zero), then abort these steps (without throwing an exception; user agents could show a message on a developer console, though, as that would be helpful for debugging).
> 3. If the number of elements in a is odd, then let a be the concatenation of two copies of a.
> 4. Let the object's dash list be a.

This is why I wanted to keep it in a central place. I can make them `protected` so they are not visible outside the package, if you like.

**Comment by p0nce** [comment]
You can make them "package:" visibility so that only printed can see them.

**Comment by p0nce** [comment]
Now in v1.0.4

**Pull request merged**
